sonar.organization=carrioneilnacr-art
sonar.projectKey=carrioneilnacr-art_Wayra_Web_Backend

sonar.projectName=Wayra Nikkei Backend
sonar.sources=controllers,services,routes,config,index.js

sonar.host.url=https://sonarcloud.io
sonar.token=78b19afcadb129eda0ab19edeb775d84af70698b
sonar.javascript.lcov.reportPaths=coverage/lcov.info